### ISSUE TITLE
Liquid error:

### ISSUE THREAD

**Issue by rijz** [Tricky3/Shopify_Infinite-Scroll#6]
I tried using this in Shopify. 

But shows this error.

Liquid error: Could not find asset snippets/product.liquid

**Comment by jayvin** [comment]
@rijz : I just noticed that we have not added the product.liquid snippet. Basically your theme should already have some structure of how the product html are rendered in the collection pages. 
To fix this, in this file: https://github.com/Tricky3/Shopify_Infinite-Scroll/blob/master/templates/collections.liquid, replace line 5 with the html content of how your products are being generated on the collection page.
